version: '3.4'

services:
  web:
    container_name: phoenix-app
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    container_name: phoenix-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    volumes:
      - phoenix-sample-data:/var/lib/postgresql/data

volumes:
  mysite.db.volume:
    name: phoenix-sample-data
